[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"


[dependencies]
crypto = "0.5.0"
sha2 = "0.10.1"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0.68"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.68"
